### ISSUE TITLE
Configuring FINS

### ISSUE THREAD

**Issue by Nani2905-AP** [Steve-Mcl/node-red-contrib-omron-fins#3]
Hi Thanks for creating the FINS Node. 

I am trying  to used the node to extract data from NX1P2 Omron CPU. 

How to Configure this part for the FINS Setting. KIndly advice. Thank you in advance
![Fins](https://user-images.githubusercontent.com/67316925/85389711-60a0a600-b57a-11ea-9738-3e8738be3c3a.JPG)

**Comment by NeltherGP** [comment]
Hi, I'm on the same boat but I dont really understand FINS I'm new to plc also working with nx1p2 and node-red

**Comment by Nani2905-AP** [comment]
have you tried Nx1p2 to node-red using Modbus TCP? 

FINS node sounds more straight forward. But currently i am also trying with Modbus TCP node.

**Comment by NeltherGP** [comment]
I have managed to read using this node 
https://flows.nodered.org/node/node-red-contrib-cip-ethernet-ip

after applying this fix 
https://github.com/netsmarttech/node-red-contrib-cip-ethernet-ip/issues/10

you can check my post here: 
https://www.reddit.com/r/PLC/comments/hefn2j/omnron_and_nodered_update/

**Comment by Steve-Mcl** [comment]
Hi all, 

I can assure you FINS communication does work (I use it in a production environment).

FINS is a fickle protocol but not too difficult to get going - you just have to understand what you are doing.

 See built in info on the node...
![image](https://user-images.githubusercontent.com/44235289/85562592-897d7580-b624-11ea-971e-52de6f30b441.png)

Generating a data area that FINS can talk to (in sysmac studio)...
![image](https://user-images.githubusercontent.com/44235289/85562713-a619ad80-b624-11ea-971b-dc22754d7cf1.png)

**Comment by Steve-Mcl** [comment]
Here is a worked example...

#### PLC 
| Setting | Value |
|----|------|
| IP | 192.168.4.88 |
| MASK | 255.255.255.0 |
| Node | 88 |
| UDP | 9600 |
 

#### Node-red 
| Setting | Value |
|----|------|
| IP | 192.168.4.179 |
| MASK | 255.255.255.0 |


#### FINS Connection Node Settings
| Option | Value |
|----|------|
Host | 192.168.4.88
Port | 9600
MODE | CS/CJ
ICF | 0x80
DNA | 0
DA1 | 88
DA2 | 0
SNA | 0
SA1 | 179
SA2 | 0





![image](https://user-images.githubusercontent.com/44235289/85577974-9c4a7700-b631-11ea-8320-99992892b39d.png)

Other notes:
* If the subnet mask is bigger than /24 (e.g. is bigger than 255.255.255.0) you might need to enter the IP and NODE number into the **IP address table** so that the PLC understands which IP to respond to when responding to the SA1 NODE number
* [This manual](https://www.edata.omron.com.au/eData/NX/W596-E1-01.pdf) has lots of info including setting up Network Numbers

**Comment by NeltherGP** [comment]
Thanks, it is working now!!

**Comment by Steve-Mcl** [comment]
@NeltherGP glad its working. :+1: 

I have updated the read.me with this info.

Please re-open if necessary or discuss on the node-red forum (you can tag me as `@Steve-Mcl` on the forum if you want to grab my attention slightly_smiling_face )

**Comment by catalinursu01** [comment]
Hello i have an omron CJ series PLC and i had some node-red code running on him for some time,after a while the plc disconnected from the node-red and now after i managed to connect it back i get timeout error.I've tried everything from this post but it seems to not work(only think i didn't try is the to change the timeout value in the node-red because i can't find the file) have you got any ideea what i can try to make it work.
