### ISSUE TITLE
"Response is NG! endCode: 2108, endCodeDescription:Write Not Possible: Cannot change."

### ISSUE THREAD

**Issue by bjornidar** [Steve-Mcl/node-red-contrib-omron-fins#5]
Hi, 

trying to figure out how to use this node with a CJ1M CPU with network card mounted on "Main rack". 
I get the error mentioned in the topic and read from another topic that this can be the com. settings. 

Are there any examples on how to setup the Read-node/ connection against a CJ1M CPU?
Any help/ suggestions are very much appreciated.

![a](https://user-images.githubusercontent.com/53019262/90768069-7a4a3980-e2ee-11ea-9002-e54d9a2eeb1a.png)
![Merknad 2020-08-21 113929](https://user-images.githubusercontent.com/53019262/90876718-539a0a80-e3a3-11ea-830c-487b5f3f2976.png)
![c](https://user-images.githubusercontent.com/53019262/90768310-ca290080-e2ee-11ea-8110-ada98ec69f31.png)

**Comment by Steve-Mcl** [comment]
Hi, 

Have you read the [read me](https://github.com/Steve-Mcl/node-red-contrib-cron-plus/blob/master/README.md) and see the built in help...
![image](https://user-images.githubusercontent.com/44235289/90958153-6afff300-e48a-11ea-88a3-0de501e917d1.png)



assuming you are connecting direct from Node-red server to PLC ETN or EIP card on the main rack...
* change DNA to `0`
* change DNA2 to `0`

If that doesn't work, try also changing DA1 to `0` also

Next...
* What is the IP address and MASK of the PLC?
* What is the IP address and MASK of  Node-red Server?
This info is important. As mentioned in the readme -  if the subnet mask is bigger than /24 (e.g. is bigger than 255.255.255.0) you might need to enter the IP and NODE number (of the node-red server) into the FINS IP address table so that the PLC understands which IP to respond to when responding to the SA1 NODE number

Next...
* What is the 2 node number dials on the Ethernet card set to?  Do they match the last octet of the PLC IP address?

**Comment by Steve-Mcl** [comment]
Closing this issue for now. Reopen if you need to. Cheers.

**Comment by bjornidar** [comment]
Just wanted to thank you for your reply. 
I've read the manual but my experience with Omron is slightly limited and the PLC I'm trying to communicate with is located on the other side of the country - will try again when I get a similar PLC beside me as I suspect it has something to do with the setup on the PLC itselft.

**Comment by bjornidar** [comment]
Ok, so - I've set up another HMI application on a Windows PC (Beijer iX) and it works flawless with these settings;
![Merknad 2020-09-08 123135](https://user-images.githubusercontent.com/53019262/92465921-96dfe000-f1cf-11ea-8536-319afd671de2.png)

Wireshark info when running iX
![Merknad 2020-09-08 124935](https://user-images.githubusercontent.com/53019262/92467555-1a023580-f1d2-11ea-9168-e471ef7b58fb.png)


Therefore, I installed Node-RED on the same PC to see if it's some kind of network issue, but these no luck
![Merknad 2020-09-08 123247](https://user-images.githubusercontent.com/53019262/92465987-b24aeb00-f1cf-11ea-8de5-503e186690e3.png)

IP-PLC: 10.50.7.8/24
IP-PC: 10.50.7.3/24
2 node number dials = PLC IP

Is it the way I connect? When using an "inject"-node with msg.topic="connect" I get the error: "TypeError: node.connection.connect is not a function".
When using "inject"-node with payload="connect" I get the error: "Response is NG! endCode: 2108, endCodeDescription:Write Not Possible: Cannot change."
